version: "3.8"
services:
  qiskit-jupyter:
    build: .
    image: qiskit-jupyter
    volumes:
      - ${PWD}/work:/home/jovyan/work
      - ${PWD}/studied:/home/jovyan/studied
      - ${PWD}/config/settings.conf:/home/jovyan/.qiskit/settings.conf
      - ${PWD}/config/ipython_kernel_config.py:/home/jovyan/.ipython/profile_default/ipython_kernel_config.py
    ports:
      - 8888:8888
    container_name: qiskit-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
